"""Intelligent Import (V2.4) - Inspector, Detector, Normalizer, Validator.

Phase 1 (the inspector) reads an Excel workbook and describes its
*structure*: workbook/sheet metadata, candidate header rows, per-column
hints and data-quality observations.  Phase 2 (the detector) interprets
that structural profile into semantic candidates - student identity,
subjects, assessments and subject-assessment pairs - carrying evidence,
confidence and explanation for every reading.  Phase 3 (the normalizer)
turns the detection into a canonical, deterministic representation that
preserves raw values and full source provenance and never guesses
ambiguous meanings.  Phase 4 (the validator) validates that representation
against deterministic, offline rules and separates errors, warnings and
review-required conditions.  Everything is deterministic: no external
calls, no AI dependencies, no storage writes, no academic decisions.
Ambiguity and conflicting evidence are preserved for human review and
never resolved silently.
"""

from assessment_engine.intelligent_import.models import (
    CellRange,
    ColumnProfile,
    ColumnRoleCandidate,
    HeaderBlock,
    HeaderCandidate,
    LayoutHints,
    SheetProfile,
    StructuralWarning,
    WorkbookProfile,
)
from assessment_engine.intelligent_import.inspector import (
    InspectorError,
    inspect_sheet,
    inspect_workbook,
    normalize_header_text,
)
from assessment_engine.intelligent_import.detector import (
    Ambiguity,
    AmbiguityOption,
    ColumnSemantics,
    Conflict,
    Evidence,
    FAMILY_ACADEMIC,
    FAMILY_ASSESSMENT,
    FAMILY_IDENTITY,
    FAMILY_ORGANIZATIONAL,
    FAMILY_SUBJECT,
    FAMILY_SUBJECT_ASSESSMENT,
    SemanticCandidate,
    SheetSemantics,
    Vocabulary,
    WorkbookDetection,
    detect_sheet,
    detect_workbook,
    vocabulary_from_config,
)
from assessment_engine.intelligent_import.normalizer import (
    ALL_VALUE_KINDS,
    CellLocation,
    NormalizedAssessment,
    NormalizedField,
    NormalizedRecord,
    NormalizedSheet,
    NormalizedValue,
    Unresolved,
    VALUE_BLANK,
    VALUE_GRADE,
    VALUE_IDENTIFIER,
    VALUE_MARK,
    VALUE_MEASURE,
    VALUE_PERCENTAGE,
    VALUE_RESULT,
    VALUE_STATUS,
    VALUE_TEXT,
    VALUE_TOTAL,
    VALUE_UNRESOLVED,
    VALUE_ZERO,
    WorkbookNormalization,
    clean_text,
    is_blank,
    normalize_grade,
    normalize_identifier,
    normalize_mark,
    normalize_measure,
    normalize_percentage,
    normalize_result,
    normalize_sheet,
    normalize_status,
    normalize_text,
    normalize_total,
    normalize_workbook,
    normalize_workbook_profile,
    parse_number,
)
from assessment_engine.intelligent_import.validator import (
    ALL_RULE_IDS,
    ALL_SEVERITIES,
    RecordValidation,
    SEVERITY_ERROR,
    SEVERITY_REVIEW,
    SEVERITY_WARNING,
    ValidationContext,
    ValidationIssue,
    ValidationResult,
    build_validation_context,
    validate_record,
    validate_workbook,
    validate_workbook_file,
)

__all__ = [
    "ALL_VALUE_KINDS",
    "ALL_RULE_IDS",
    "ALL_SEVERITIES",
    "Ambiguity",
    "AmbiguityOption",
    "CellLocation",
    "CellRange",
    "ColumnProfile",
    "ColumnRoleCandidate",
    "ColumnSemantics",
    "Conflict",
    "Evidence",
    "FAMILY_ACADEMIC",
    "FAMILY_ASSESSMENT",
    "FAMILY_IDENTITY",
    "FAMILY_ORGANIZATIONAL",
    "FAMILY_SUBJECT",
    "FAMILY_SUBJECT_ASSESSMENT",
    "HeaderBlock",
    "HeaderCandidate",
    "InspectorError",
    "LayoutHints",
    "NormalizedAssessment",
    "NormalizedField",
    "NormalizedRecord",
    "NormalizedSheet",
    "NormalizedValue",
    "RecordValidation",
    "SEVERITY_ERROR",
    "SEVERITY_REVIEW",
    "SEVERITY_WARNING",
    "SemanticCandidate",
    "SheetProfile",
    "SheetSemantics",
    "StructuralWarning",
    "Unresolved",
    "VALUE_BLANK",
    "VALUE_GRADE",
    "VALUE_IDENTIFIER",
    "VALUE_MARK",
    "VALUE_MEASURE",
    "VALUE_PERCENTAGE",
    "VALUE_RESULT",
    "VALUE_STATUS",
    "VALUE_TEXT",
    "VALUE_TOTAL",
    "VALUE_UNRESOLVED",
    "VALUE_ZERO",
    "ValidationContext",
    "ValidationIssue",
    "ValidationResult",
    "Vocabulary",
    "WorkbookDetection",
    "WorkbookNormalization",
    "WorkbookProfile",
    "build_validation_context",
    "clean_text",
    "detect_sheet",
    "detect_workbook",
    "inspect_sheet",
    "inspect_workbook",
    "is_blank",
    "normalize_grade",
    "normalize_header_text",
    "normalize_identifier",
    "normalize_mark",
    "normalize_measure",
    "normalize_percentage",
    "normalize_result",
    "normalize_sheet",
    "normalize_status",
    "normalize_text",
    "normalize_total",
    "normalize_workbook",
    "normalize_workbook_profile",
    "parse_number",
    "validate_record",
    "validate_workbook",
    "validate_workbook_file",
    "vocabulary_from_config",
]